const PYTHON_BOOTSTRAP_LINES = [
  "import json",
  "import sys",
  'from pathlib import Path',
  '',
  '_RUNTIME_ROOT = Path("/code_visualizer_runtime")',
  'if str(_RUNTIME_ROOT) not in sys.path:',
  '    sys.path.insert(0, str(_RUNTIME_ROOT))',
  '',
  'def _require_browser_dependencies():',
  '    diagnostics = []',
  '    checks = [',
  '        ("step_tracer", "import step_tracer"),',
  '        ("step_tracer.StepTracer", "from step_tracer import StepTracer"),',
  '        ("query_engine", "import query_engine"),',
  '        ("query_engine.QueryEngine", "from query_engine import QueryEngine"),',
  '    ]',
  '    for label, statement in checks:',
  '        try:',
  '            exec(statement, globals())',
  '        except Exception as exc:',
  '            diagnostics.append(f"{label}: {exc!r}")',
  '    if diagnostics:',
  '        raise RuntimeError("Browser dependency import failed:\\n" + "\\n".join(diagnostics))',
  '',
  '_require_browser_dependencies()',
  '',
  'from code_visualizer import ViewKind, default_visualizer_config, visualize_algorithm_manifest_payload',
  '',
  'def run_visualization(payload_json: str):',
  '    payload = json.loads(payload_json)',
  '    config_payload = payload.get("config") or {}',
  '    config = default_visualizer_config()',
  '',
  '    step_limit = config_payload.get("step_limit")',
  '    if step_limit is not None:',
  '        config.trace_step_limit_default = step_limit',
  '',
  '    output_format = config_payload.get("output_format")',
  '    if output_format:',
  '        config.output_format = output_format',
  '',
  '    max_depth = config_payload.get("max_depth")',
  '    if max_depth is not None:',
  '        config.max_depth = max_depth',
  '',
  '    max_items_per_view = config_payload.get("max_items_per_view")',
  '    if max_items_per_view is not None:',
  '        config.max_items_per_view = max_items_per_view',
  '',
  '    recursion_depth_default = config_payload.get("recursion_depth_default")',
  '    if recursion_depth_default is not None:',
  '        config.recursion_depth_default = recursion_depth_default',
  '',
  '    auto_recursion_depth_cap = config_payload.get("auto_recursion_depth_cap")',
  '    if auto_recursion_depth_cap is not None:',
  '        config.auto_recursion_depth_cap = auto_recursion_depth_cap',
  '',
  '    show_titles = config_payload.get("show_titles")',
  '    if show_titles is not None:',
  '        config.show_titles = bool(show_titles)',
  '',
  '    type_view_defaults = config_payload.get("type_view_defaults") or {}',
  '    for type_pattern, view_kind in type_view_defaults.items():',
  '        if view_kind and view_kind != "auto":',
  '            config.view_type_map[type_pattern] = ViewKind(view_kind)',
  '',
  '    variable_configs = config_payload.get("variable_configs") or {}',
  '    for variable_name, variable_config in variable_configs.items():',
  '        view_kind = variable_config.get("view_kind")',
  '        if view_kind and view_kind != "auto":',
  '            config.view_name_map[variable_name] = ViewKind(view_kind)',
  '        depth = variable_config.get("depth")',
  '        if depth is not None:',
  '            config.recursion_depth_map[variable_name] = depth',
  '        max_steps = variable_config.get("max_steps")',
  '        if max_steps is not None:',
  '            config.trace_step_limit_map[variable_name] = max_steps',
  '',
  '    result = visualize_algorithm_manifest_payload(',
  '        payload["snippet"],',
  '        watch_variables=payload.get("watch"),',
  '        config=config,',
  '    )',
  '    return json.dumps(result)',
];

export const PYTHON_BOOTSTRAP = PYTHON_BOOTSTRAP_LINES.join("\n");
