from __future__ import annotations

FONT_FAMILY = "Helvetica"

TEXT_PRIMARY = "#0f172a"
TEXT_MUTED = "#94a3b8"
TEXT_SECONDARY = "#475569"
TEXT_INDEX = "#dc2626"
TEXT_WARNING = "#b45309"
ELLIPSIS_TEXT = "#64748b"

BORDER_DEFAULT = "#cbd5e1"
BORDER_MUTED = "#e2e8f0"
BORDER_DARK = "#4b5563"
BORDER_CHAIN = "#6b7280"
BORDER_FOCUS = "#60a5fa"
BORDER_STRONG = "#2563eb"
BORDER_TREE = "#1f2933"
BORDER_ROW_HEADER = "#f8dca3"
BORDER_CELL_FOCUS = "#f59e0b"

BG_SURFACE = "#ffffff"
BG_PANEL = "#f8fafc"
BG_HEADER = "#e5e7eb"
BG_HEADER_MUTED = "#f3f4f6"
BG_FOCUS = "#dbeafe"
BG_FOCUS_SOFT = "#eff6ff"
BG_PREVIEW = "#eef2ff"
BG_ROW_HEADER = "#fef3c7"
BG_ROW_HEADER_FOCUS = "#fde68a"
BG_CELL_FOCUS = "#fff7ed"
BG_BAR_POSITIVE_SOFT = "#bae6fd"
BG_BAR_NEGATIVE_SOFT = "#fecaca"

FILL_BAR_POSITIVE = "#2563eb"
FILL_BAR_NEGATIVE = "#dc2626"

TITLE_FONT_SIZE = 16
SUBTITLE_FONT_SIZE = 10
BODY_FONT_SIZE = 11
INDEX_FONT_SIZE = 12

TEXT_NULL = "#9ca3af"
